config/routes.rb
TwelveParsecs::Application.routes.draw do
  
  root to: 'parsecs#index'

  get '/login', to: 'sessions#new'
  post '/sessions', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/parsecs/search', to: 'parsecs#search'

  resources :users
  resources :parsecs
  resources :comments
  resources :parsec_user_votes
  resources :comment_user_votes

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :parsec

	has_many :comment_user_votes, dependent: :destroy

	def update_score
		self.comment_user_votes.inject(0) {|total, vote_obj| total + vote_obj.vote}
	end
	
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def show
		@comment = Comment.find(params[:id])
	end
		
	def create
		@user = current_user
		@parsec = Parsec.find(params[:comment][:parsec_id])
		@comment = Comment.create(comment_params)
		@comment.user_id = @user.id
		@comment.parsec_id = @parsec.id
		@comment.time = Time.now
		@comment.score = 0
		@comment.save
			redirect_to @parsec
	end

	def edit
		@comment = Comment.find(params[:id])
	end

	def update
		@comment = Comment.find(params[:id])
		@parsec = @comment.parsec
		@comment.body = params[:comment][:body]
		@comment.save
		redirect_to @parsec
	end

	def destroy
		@comment = Comment.find(params[:id])
		@parsec = @comment.parsec
		if @comment.destroy
			redirect_to @parsec
		else
			redirect_to edit_comment_path(@comment)
		end
	end

	private

	def comment_params
		params.require(:comment).permit(:body)
	end

end

app/views/comments/_comment_vote_logic.html.erb
	<% if user_comment_vote_log.include?(comment.id) %>
	<% old_vote = user.comment_user_votes.find_by(comment_id: comment.id) %>
		<% if old_vote.vote == 1 %>
			<%= render partial: "comments/comment_voted_up", locals: {comment: comment, old_vote: old_vote} %>
		<% elsif old_vote.vote == -1 %>
			<%= render partial: "comments/comment_voted_down", locals: {comment: comment, old_vote: old_vote}  %>
		<% end %>
	<% else %>
		<%= render partial: "comments/comment_vote_new", locals: {comment: comment}  %>
<% end %>

app/views/comments/_comment_vote_new.html.erb
<!-- no votes -->

<%= form_for(@comment_user_vote, url: comment_user_votes_path, html: {method: "post", class: "parsec-vote-up"}) do |f| %>
	<%= f.hidden_field(:vote, value: 1)%>
	<%= f.hidden_field(:comment_id, value: comment.id)%>
	<%= f.submit("Upvote") %>
<% end %>

<%= comment.score %>

<%= form_for(@comment_user_vote, url: comment_user_votes_path, html: {method: "post", class: "parsec-vote-down"}) do |f| %>
	<%= f.hidden_field(:vote, value: -1)%>
	<%= f.hidden_field(:comment_id, value: comment.id)%>
	<%= f.submit("Downvote") %>
<% end %>

app/views/comments/_comment_voted_down.html.erb
<!-- already downvoted -->

<%= form_for(@comment_user_vote, url: comment_user_vote_path(old_vote.id), html: {method: "patch", class: "parsec-vote-up"}) do |f| %>
	<%= f.hidden_field(:vote, value: 1)%>
	<%= f.submit("Upvote") %>
<% end %>

<%= comment.score %>

<%= form_for(@comment_user_vote, url: comment_user_vote_path(old_vote.id), html: {method: "delete", class: "parsec-voted-down"}) do |f| %>
	<%= f.submit("Unvote") %>
<% end %>

app/views/comments/_comment_voted_up.html.erb
<!-- already upvoted -->

<%= form_for(@comment_user_vote, url: comment_user_vote_path(old_vote.id), html: {method: "delete", class: "parsec-voted-up"}) do |f| %>
	<%= f.submit("Unvote") %>
<% end %>

<%= comment.score %>

<%= form_for(@comment_user_vote, url: comment_user_vote_path(old_vote.id), html: {method: "patch", class: "parsec-vote-down"}) do |f| %>
	<%= f.hidden_field(:vote, value: -1)%>
	<%= f.submit("Downvote") %>
<% end %>

app/views/comments/edit.html.erb
<%= form_for(@comment, url: {action: "update"}, html: {class: "comment-form"}) do |f| %>
	<div>
		<%= f.label(:body, "Edit Comment:") %>
		<%= f.text_field(:body) %>
	</div>
	<div>
		<%= f.submit("Save Changes") %>
	</div>
<% end %>

<h1>Or...</h1>

<%= form_tag(comment_path, method: "delete", html: {class: "comment-form"}) do %>

	<%=submit_tag("Delete Comment For Eternity")%>

<% end %>