config/routes.rb
TwelveParsecs::Application.routes.draw do
  
  root to: 'parsecs#index'

  get '/login', to: 'sessions#new'
  post '/sessions', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/parsecs/search', to: 'parsecs#search'

  resources :users
  resources :parsecs
  resources :comments
  resources :parsec_user_votes
  resources :comment_user_votes

end

app/models/parsec.rb
class Parsec < ActiveRecord::Base

	belongs_to :user
	has_many :comments, dependent: :destroy
	has_many :parsec_user_votes, dependent: :destroy

	def update_score
		self.parsec_user_votes.inject(0) {|total, vote_obj| total + vote_obj.vote}
	end

	def self.title_search(search_term)
		if search_term != nil
			if search_term.split(' ').length > 1
				search_term = search_term.split(' ')
				search_term = search_term.join('+')
			end
			raw_results = httparty_get("http://www.imdb.com/xml/find?json=1&nr=1&tt=on&q=#{search_term}")
			results = parse_json(raw_results)
			return results
		end
	end

	def self.omdb_search(search_term)
			results = httparty_get("http://www.omdbapi.com/?i=#{search_term}")
			results = parse_json(results)
			return results
	end

	def self.rotten_tomatoes_poster(search_term)
			api_key = ENV['RT_API_KEY']
			title = URI.escape(search_term)
			results = httparty_get("http://api.rottentomatoes.com/api/public/v1.0/movies.json?apikey=#{api_key}&q=#{title}")
			results = parse_json(results)
			poster = results["movies"][0]["posters"]["detailed"]
			return poster
	end

	def self.httparty_get(url)
		return HTTParty.get(url)
	end

	def self.parse_json(response)
		return JSON.parse(response)
	end

end

app/controllers/parsecs_controller.rb
class ParsecsController < ApplicationController

	before_action :authorize, only: [:edit, :update, :destroy]

	def index
		@user = current_user
		@parsecs = Parsec.order(score: :desc)
		@parsecs = @parsecs.first(100) #Top 100 Parsecs
		if @user != nil
			@user_vote_log = @user.parsec_user_votes.map {|vote| vote.parsec_id}
		else
			@user_vote_log = []
		end
		@parsec_user_vote = ParsecUserVote.new
	end

	def show
		@user = current_user
		@parsec = Parsec.find(params[:id])
		@comment = Comment.new
		if @user != nil
			@user_vote_log = @user.set_parsec_vote_log
			@user_comment_vote_log = @user.set_comment_vote_log
		else
			@user_vote_log = []
			@user_comment_vote_log = []
		end
		@parsec_user_vote = ParsecUserVote.new
		@comment_user_vote = CommentUserVote.new
		@associated_title = Parsec.omdb_search(@parsec.imdb_id)
		@associated_title["Poster"] = Parsec.rotten_tomatoes_poster(@associated_title["Title"])
		render :layout => "parsec_show"
	end

	def new
		if session[:user_id]
			@parsec = Parsec.new
			@search_results = Parsec.title_search(params[:search_term])
			if params[:associated_title]
				@associated_title = Parsec.omdb_search(params[:associated_title])
				@associated_title["Poster"] = Parsec.rotten_tomatoes_poster(@associated_title["Title"])
			else
				@associated_title={"imdbID" => "none"}
			end
		else
			redirect_to login_path
		end
	end

	def create
		@user = current_user
		@parsec = Parsec.create(parsec_params)
		@parsec.media_id = 0
		@parsec.user_id = @user.id
		@parsec.score = 0
		@parsec.time = Time.now
		if @parsec.save
			redirect_to @parsec
		else
			redirect_to new_parsec_path
		end
	end

	def edit
		@parsec = Parsec.find(params[:id])
	end

	def update
		@parsec = Parsec.find(params[:id])
		if @parsec.update(parsec_params)
			redirect_to @parsec
		else
			redirect_to edit_parsec_path(@parsec)
		end
	end

	def destroy
		@parsec = Parsec.find(params[:id])
		if @parsec.destroy
			redirect_to user_path(current_user)
		else
			redirect_to parsec_path(@parsec)
		end
	end

	def title_search
		@search_results = Parsec.title_search(params[:search_term])
			redirect_to action: 'new'
	end

	def search
		@search_results = Parsec.title_search(params[:search_term])
		if params[:associated_title]
			@associated_title_id = params[:associated_title]
			@associated_title = Parsec.omdb_search(params[:associated_title])
			@associated_title["Poster"] = Parsec.rotten_tomatoes_poster(@associated_title["Title"])
		else
			@associated_title = nil
		end
	end

	private

	def parsec_params
		params.require(:parsec).permit(:title, :body, :imdb_id)
	end

	def authorize
		parsec = Parsec.find(params[:id])
		if parsec.user != current_user
			redirect_to parsec_path(parsec)
		end
	end

end

app/views/parsecs/_parsec_info_side.html.erb
<div class="parsec-column-1">
		<h2><a href="/parsecs/search?associated_title=<%=associated_title["imdbID"]%>"><%= associated_title["Title"] %></a></h2>
		<img src="<%=associated_title["Poster"]%>" class="poster-info">
		<br>
		<div class="title-info-list">
			<ul>
				<li>Director: <%= associated_title["Director"] %></li>
				<li>Writer: <%= associated_title["Writer"] %></li>
				<li>Runtime: <%= associated_title["Runtime"] %></li>
				<li>Genre: <%= associated_title["Genre"] %></li>
				<li>Plot: <%= associated_title["Plot"] %></li>
				<li>Actors: <%= associated_title["Actors"] %></li>
			</ul>
		</div>
	</div>

app/views/parsecs/_parsec_vote_logic.html.erb
<% if user_vote_log.include?(parsec.id) %>
	<% old_vote = user.parsec_user_votes.find_by(parsec_id: parsec.id) %>
		<% if old_vote.vote == 1 %>
			<%= render partial: "parsec_voted_up", locals: {parsec: parsec, old_vote: old_vote} %>
		<% elsif old_vote.vote == -1 %>
			<%= render partial: "parsec_voted_down", locals: {parsec: parsec, old_vote: old_vote}  %>
		<% end %>
	<% else %>
		<%= render partial: "parsec_vote_new", locals: {parsec: parsec}  %>
<% end %>

app/views/parsecs/_parsec_vote_new.html.erb
<!-- no votes -->

<%= form_for(@parsec_user_vote, url: parsec_user_votes_path, html: {method: "post", class: "parsec-vote-up"}, ) do |f| %>
	<%= f.hidden_field(:vote, value: 1)%>
	<%= f.hidden_field(:parsec_id, value: parsec.id)%>
	<%= f.submit("Upvote") %>
<% end %>

<%= parsec.score %>

<%= form_for(@parsec_user_vote, url: parsec_user_votes_path, html: {method: "post", class: "parsec-vote-down"}) do |f| %>
	<%= f.hidden_field(:vote, value: -1)%>
	<%= f.hidden_field(:parsec_id, value: parsec.id)%>
	<%= f.submit("Downvote") %>
<% end %>

app/views/parsecs/_parsec_voted_down.html.erb
<!-- already downvoted -->

<%= form_for(@parsec_user_vote, url: parsec_user_vote_path(old_vote.id), html: {method: "patch", class: "parsec-vote-up"}) do |f| %>
	<%= f.hidden_field(:vote, value: 1)%>
	<%= f.submit("Upvote") %>
<% end %>

<%= parsec.score %>

<%= form_for(@parsec_user_vote, url: parsec_user_vote_path(old_vote.id), html: {method: "delete", class: "parsec-voted-down"}) do |f| %>
	<%= f.submit("Unvote") %>
<% end %>

app/views/parsecs/_parsec_voted_up.html.erb
<!-- already upvoted -->

<%= form_for(@parsec_user_vote, url: parsec_user_vote_path(old_vote.id), html: {method: "delete", class: "parsec-voted-up"}) do |f| %>
	<%= f.submit("Unvote") %>
<% end %>

<%= parsec.score %>

<%= form_for(@parsec_user_vote, url: parsec_user_vote_path(old_vote.id), html: {method: "patch", class: "parsec-vote-down"}) do |f| %>
	<%= f.hidden_field(:vote, value: -1)%>
	<%= f.submit("Downvote") %>
<% end %>

app/views/parsecs/_show_header.html.erb
<div class="container">
	<div class="column-1">
		<h1><%= render partial: "parsec_vote_logic", locals: {parsec: @parsec, user: @user, user_vote_log: @user_vote_log} %></h1>
	</div>
	<div class="column-2-1">
			<h1><%= @parsec.title %></h1>
	</div>
	<div class="column-2-2">
		<img src="<%= @parsec.user.avatar_url%>" class="big-avatar">
		by: <%= link_to(@parsec.user.name, @parsec.user) %> NerdCred: <% @parsec.user.calculate_nerd_score %> <%= @parsec.user.nerd_cred_score %>
	</div>
	<div class="footer"></div>
</div>

app/views/parsecs/edit.html.erb
<%= form_for(@parsec, url: {action: "update"}, html: {class: "parsec-form"}) do |f|%>
<div>
	<%= f.label :title, "Edit Parsec Title:" %>
	<%= f.text_field :title, value: @parsec.title%>
</div>

<div>
	<%= f.label :body, "Edit Parsec Info:" %>
	<%= f.text_area :body, value: @parsec.body%>

</div>

<div>
	<%= f.submit("Save Changes") %>
</div>
<% end %>

<h1>OR...</h1>

<%= form_tag(parsec_path, method: :delete, html: {class: "parsec-delete-form"}) do%>
	<%=submit_tag("DELETE THIS PARSEC FOREVERRRRR")%>
<% end %>

app/views/parsecs/index.html.erb
<div align="center">
	<h1>Top Parsecs</h1>
</div>


<% @parsecs.each do |parsec| %>
	<div>
		<table>
			<tr>
				<td width="100" valign="middle" align="center"> 
					<div class="parsec-index-line">
						<%= render partial: "parsec_vote_logic", locals: {parsec: parsec, user: @user, user_vote_log: @user_vote_log} %>
					</div>
				</td>
				<td width="650" valign="middle">
						<div class="parsec-index-line">
						<%= link_to(parsec.title, parsec) %>
						</div>
				</td>
				<td>
					by <a href="/users/<%= parsec.user.id%>"><img src="<%=parsec.user.avatar_url%>" class="avatar"><%= parsec.user.name %></a> <% parsec.user.calculate_nerd_score %> <%= parsec.user.nerd_cred_score %>
				</td>
			</tr>
		</table>
	</div>
<% end %>

app/views/parsecs/new.html.erb
<% if @associated_title["imdbID"] != "none" %>
	<h1>Creating Parsec For <%= @associated_title["Title"] %> - <%= @associated_title["Year"] %></h1>
	<img src="<%= @associated_title["Poster"]%>">
<% end %>

<% if @search_results != nil %>
	<ul>
		<% @search_results["title_popular"].each do |result| %>
			<div>
				<li>
					<a href="/parsecs/new?associated_title=<%=result["id"]%>">
					<%= result["title"].html_safe %></a> | 
					<% description = result["description"].split(',') %>
					<%= description[0].html_safe %>
				</li>
			</div>
		<% end %>
		<% if @search_results["title_exact"] != nil %>
			<% @search_results["title_exact"].each do |result| %>
			<div>
					<li>
						<a href="/parsecs/new?associated_title=<%=result["id"]%>">
						<%= result["title"].html_safe %></a> | 
						<% description = result["description"].split(',') %>
						<%= description[0].html_safe %>
					</li>
				</div>
			<% end %>
		<% end %>
	</ul>
<% else %>
	<%= form_tag("/parsecs/new", method: "get", html: {class: "make-comment-form"}) do %>
		<%= label_tag(:search_term, "Enter a movie, show, or game to search for:") %> 
		<%= text_field_tag(:search_term) %> 
		<%= submit_tag("Search!") %>
	<% end %>
<% end %>


<%= form_for(@parsec, url: {action: "create"}, html: {class: "parsec-form"}) do |f| %>
	<div>
		<%= f.label :title, "Start a Parsec! (Ex: \"In Ghostbusters, why did Peter Venkman have 300cc's of Thorazine on his date with Dana?\")", value: "Parsec Title!"%>
		<%= f.text_field :title, value: "Parsec Title!" %>
	</div>
	<div>
		<%= f.label :body, "(Optional) Explanation:" %>
		<%= f.text_area :body, value: "Example: \"I've watched this scene a thousand times and can't figure out why he brought tons of antipsychotics with him to dinner.\""%>
	</div>
		<%= f.hidden_field(:imdb_id, value: @associated_title["imdbID"]) %> 
	<div>
		<%= f.submit "Create Parsec!" %>
	</div>
<% end %> 

app/views/parsecs/search.html.erb
<div class="parsec-body">

<% if @search_results %>
	<ul>
		<!-- top results -->
		<% if @search_results["title_popular"] != nil %>
			<% @search_results["title_popular"].each do |result| %>
				<div>
					<li>
						<a href="/parsecs/search?associated_title=<%=result["id"]%>">
						<%= result["title"].html_safe %></a> | 
						<% description = result["description"].split(',') %>
						<%= description[0].html_safe %>
					</li>
				</div>
			<% end %>
		<% end %>

			<!-- lower results -->
		<% if @search_results["title_exact"] != nil  %>
			<% @search_results["title_exact"].each do |result| %>
			<div>
					<li>
						<a href="/parsecs/search?associated_title=<%=result["id"]%>">
						<%= result["title"].html_safe %></a> | 
						<% description = result["description"].split(',') %>
						<%= description[0].html_safe %>
					</li>
				</div>
			<% end %>
		<% end %>

		<!-- lowest results -->
		<% if @search_results["title_substring"] != nil  %>
			<% @search_results["title_substring"].each do |result| %>
			<div>
					<li>
						<a href="/parsecs/search?associated_title=<%=result["id"]%>">
						<%= result["title"].html_safe %></a> | 
						<% description = result["description"].split(',') %>
						<%= description[0].html_safe %>
					</li>
				</div>
			<% end %>
		<% end %>
		</ul>

	<!-- if we searched for SOMETHING, but got NOTHING, tell the user -->
	<% if @search_results["title_popular"] == nil && @search_results["title_exact"] == nil && @search_results["title_substring"] == nil %>
		<h2>Sorry, no results found for <%= params[:search_term] %></h2>
	<% end %>
<% end %>
<!-- end of search results stuff -->

<!-- now the results for Parsecs based off selected title from search results -->
<% if @associated_title != nil %>

<%= render partial: "parsec_info_side", locals: {associated_title: @associated_title} %>

	<% parsecs = Parsec.where(imdb_id: @associated_title_id) %>
	<% parsecs.order(score: :desc) %>

	<ul>
		<% parsecs.each do |parsec| %>
			<li>
				<%= link_to(parsec.title, parsec) %> by <%=parsec.user.name%> <img src="<%=parsec.user.avatar_url%>" class="avatar">
			</li>
		<% end %>
	</ul>

	<% if parsecs.length == 0 %>
			<h2> No Parsecs found for this title :( </h2>
			<h1><%= link_to("Create one?", "/parsecs/new?associated_title=#{@associated_title}") %></h1>
	<% end %>


<% end %>

</div>

app/views/parsecs/show.html.erb
<div class="parsec-container">

	<!-- INFO SIDE -->

	<%= render partial: "parsec_info_side", locals: {associated_title: @associated_title} %>



	<!-- COMMENTS SIDE -->

	<div class="parsec-column-2">

		<!-- edit your parsec -->
		<% if @parsec.user == current_user %>
			<div class="more-info">
				<%= link_to("Edit Your Parsec", edit_parsec_path)%>
			</div>
		<% end %>

		<% if params[:message] %>
			<h1>(Error: <%= params[:message] %>)</h1>
		<% end %>
	

		<!-- leave a comment -->
		<% if current_user %>
				<h1>Dude, because...</h1>
					<%=form_for(@comment, method: "create", html: {class: "make-comment-form"}) do |f|%>
							<%= f.hidden_field(:parsec_id, value: "#{params[:id]}")%>
						<div>
							<%= f.text_field :body %>
						</div>
						<div>
						<%= f.submit "...like, that's why, man.", id: "make-comment-submit" %>
					</div>
				<% end %>

		<% else %>

		<!-- Not logged in -->
			<h1>Because... <%=link_to("[Login to Answer!]", login_path)%></h1>

		<% end %>

			<!-- more info -->
		<div class="parsec-body">
			<p>
				by <%= @parsec.user.name %> @ <%= @parsec.time %> | More Info:
			<br><br>
				<%= @parsec.body %>
			</p>
		</div>


		<!-- COMMENTS SECTION -->

			<% comments = @parsec.comments.order(score: :desc) %>

			<% comments.each do |comment| %>

				<div class="comment-vote">
					<%= render partial: "comments/comment_vote_logic", locals: {comment: comment, user: @user, user_comment_vote_log: @user_comment_vote_log} %>
				</div> 

				<div class="comment-body">
					<%= comment.body %>

					<% if current_user && comment.user.id == current_user.id %>
					<br>
						<%= link_to("Edit My Comment", edit_comment_path(comment))%>
					<% end %>
				</div>

				<div class="comment-author">
					<img src="<%=comment.user.avatar_url%>" class="avatar"><br>
					by: <%=link_to(comment.user.name, comment.user)%>
					<%comment.user.calculate_nerd_score%>
					 (<%=comment.user.nerd_cred_score%>)
				</div>

			
			<% end %>

			
			</div>
		</div>

	</div>

</div>