config/routes.rb
TwelveParsecs::Application.routes.draw do
  
  root to: 'parsecs#index'

  get '/login', to: 'sessions#new'
  post '/sessions', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/parsecs/search', to: 'parsecs#search'

  resources :users
  resources :parsecs
  resources :comments
  resources :parsec_user_votes
  resources :comment_user_votes

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>12Parsecs</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
	
	<div align="center">
		<a href="/">
			<%= image_tag "parsecslogo.png", class: "logo" %>
		</a>
	</div>

<div class="menu">
	<% if current_user %>
		Hello, <%= current_user.name %> | <%= link_to "Logout", logout_path %>
	<% else %>
		<%= link_to "Login", login_path %> or <%= link_to "Create Account", new_user_path %>
	<% end %>

</div>

<div class="menu">

	<a href="/">Home</a> | 
	<a href="/users">Users</a> | 
	<a href="/parsecs">Parsecs</a> | 
	<% if current_user %>
	<a href="/parsecs/new">New Parsec</a> | 
	<% end %>

</div>

	<div class="search-box">
		<h2>
		<%= form_tag("/parsecs/search", method: "get") do %>
		<%= label_tag(:search_term, "Search Parsecs by Movie, TV Show, or Video Game:") %> 
		<%= text_field_tag(:search_term) %> 
		<%= submit_tag("Search!") %>
		<% end %>
		</h2>
	</div>
	
</div>
</header>


<%= yield %>

</body>
</html>

app/views/layouts/parsec_show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>12Parsecs</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>

<div class="header-container">	

	<div class="search-box">
		<%= form_tag("/parsecs/search", method: "get", html: {class: "home-search-form"}) do %>
										<%= label_tag(:search_term, "Search Parsecs by Movie, TV Show, or Video Game:") %> 
			<%= text_field_tag(:search_term) %> 
			<%= submit_tag("Search!") %>
		<% end %>
	</div>

	<%= image_tag "parsecslogo-sm.png", class: "mini-logo" %>

	<div class="menu">
		<% if current_user %>
			Hello, <%= current_user.name %> | <%= link_to "Logout", logout_path %>
		<% else %>
			<%= link_to "Login", login_path %> or <%= link_to "Create Account", new_user_path %>
		<% end %>
	</div>

	<div class="menu">
		<a href="/">Home</a> | 
		<a href="/users">Users</a> | 
		<a href="/parsecs">Parsecs</a> | 
		<% if current_user %>
			<a href="/parsecs/new">New Parsec</a> | 
		<% end %>
	</div>
</div>

<div class="parsec-header-container">

	<%= render partial: "show_header" %>

</div>
</header>


<%= yield %>

</body>
</html>